zkp/contracts/FToken.sol

Fix https://github.com/EYBlockchain/nightfall/issues/7

FToken: add missing return statements on transfer/approve

---

zkp/contracts/Pairing_v1.sol

fixes #14 
I've used the latest version in ZoKrates (https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_core/src/proof_system/bn128/utils/solidity.rs) 
I haven't used https://github.com/musalbas/solidity-BN256G2/blob/master/BN256G2.sol 
Although this has ~20,000 lower gas cost, I'll assume more eyes have looked over the version sitting in ZoKrates currently.
All zkp test scripts passed.

fix: fixes #14 update G2 lib to ZoKrates' latest implementation

---

README.md
zkp/code/gm17/ft-burn/ft-burn.pcode
zkp/code/gm17/nft-burn/nft-burn.pcode
zkp/contracts/FTokenShield.sol
zkp/contracts/NFTokenShield.sol
zkp/contracts/Pairing_v1.sol
zkp/src/f-token-controller.js
zkp/src/f-token-zkp.js
zkp/src/nf-token-controller.js
zkp/src/nf-token-zkp.js

fixes #19
See README: added a 'Security Updates' section. When testing, please follow the steps in this section, to ensure they're correct.
Let's **tag** important security updates. (Let's also tag the first commit as v1.0.0).
See code changes to address the payTo bug.

fixes #19 Michaelconnor/burn payto fix

---

database/src/business/coin.service.js
ui/src/app/pages/spend-coin/spend-coin.component.ts
ui/src/app/services/coins/coin-api.service.ts

-- Fixed: Zero change OpsCoin commitment issue
-- Filter out zero OpsCoin commitment from listing page
fixes#32

fix:transferring full balance of OpsCoin commitments results in an error

---

zkp/contracts/FTokenShield.sol

Use the ERC-20 interface instead of fungible token implementation in `FTokenShield.sol`.

FTokenShield interface for FT

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This update adds a issue template and a pull request template to the repo.
This should help of achieve uniform issue and pull request messages.

feat: adding issue and commit templates

---

zkp-demo

In case
```sh
docker-compose down -v
```
fails to remove network and volume. this update will explicitly remove them 
By running bash script ./zkp-demo

fix: restarting zkp-demo script now clear db data

---

ui/src/app/pages/burn-public-coin/burn-public-coin.component.ts

Fixed the issue when ERC20 burn fails if amount burned greater than holdings.
UI gets hangs and throwing contract error when user enters a higher value than his holdings on ERC-20 token burn.  Fixed by checking the enter value is greater that he have and shows a toast message in UI. 
Tested using UI

fix(ui): ERC20 burn fails if amount burned > holdings.

---

zkp-utils/package.json

Adds repository information to zkp-utils package
#93
Warnings represent failure to adhere to best practice. Removing warnings moves towards adopting best practices.
Run `npm install` from the zkp-utils directory after the update.
n/a
- [b] All new and existing tests passed.

Adds repository information to zkp-utils package, fixes #93

---

.travis.yml

This updates the test suite to run the prepare step.

Update test suite

---

database/response/response.js
database/script_to_configure_roles.js
database/src/business/accounts.service.js
database/src/business/coin.service.js
database/src/business/coin_transaction.service.js
database/src/business/token.service.js
database/src/common/constants.json
database/src/config.js
database/src/index.js
database/src/mappers/coin-transaction.js
database/src/mappers/token-transaction.js
database/src/mappers/user.js
database/src/mongodb/db.js
database/src/routes/response/response.js

fixes eslint error of database microservice.
fixes#105
1. by running integration test
2. by using UI.

Liju.jose/105 fix database eslint

---

ui/src/app/services/accounts/accounts-api.service.ts

fixes UI bug
fixes#123
currently UI is broken as two APIs got changed for zkp microservice.
1. by running integration test
2. and by using UI.

fixes ui with updated changed zkp api

---

ui/angular.json
ui/src/app/feature/nav/nav.component.html
ui/src/index.html

Changing a few old titles to say nightfall rather than zkp demo
- [ x] My code follows the code style of this project.
- [ x] All new and existing tests passed.

fix(UI): change ZKPDemo UI titles to Nightfall

---

api-gateway/src/rest/offchain.js
api-gateway/src/services/api-gateway.js
api-gateway/src/services/ft-commitment.js
api-gateway/src/services/ft.js
api-gateway/src/services/nft-commitment.js
api-gateway/src/services/nft.js
api-gateway/src/services/whisper.js
docker-compose.test.yml
docker-compose.yml
offchain/response/index.js
offchain/src/index.js
offchain/src/middlewares/index.js
offchain/src/middlewares/response.js
offchain/src/routes/pkd.js
offchain/src/routes/whisper.js

created a response middleware and handled all response using it, for both success and failure
fixes#126
1. by running integration test
2. by using UI.

response middleware for offchain microservice

---

README.md

This PR correct some spelling and grammatical mistake in README.md

README.md corrected for integration test information

---

accounts/config/default.js
accounts/config/default.json
accounts/config/test.js
accounts/config/test.json
accounts/src/web3.js

used configuration settings using config module rather than setting ENV directly wherever its needed
fixes#146
1. integtration test
2. by running UI

config module usage corrected for accounts microservice

---

.eslintrc.js
docker-entrypoint-initdb.d/01_setup_admin_user.js
integration-test/test.js
integration-test/testData.js
zkp/src/middlewares/response.js

fixes eslint issues for left-out files
fixes#151
1.  Integration test
2.  By running UI

fixes leftout eslint issues

---

README.md

This is a PR to update Readme file with commands for Linux users.
The update is required for those users, who setup application in Linux os.

Readme file update for Linux users

---

README.md
api-gateway/src/rest/offchain.js
api-gateway/src/services/whisper.js
doc/whitepaper/nightfall-v1.tex
doc/whitepaper/protocols/ERC20/mint20.tex
doc/whitepaper/protocols/ERC20/transfer20.tex
doc/whitepaper/protocols/ERC721/mint721.tex
doc/whitepaper/protocols/ERC721/transfer721.tex
offchain/src/routes/whisper.js
offchain/src/whisper-controller-stub.js
offchain/src/whisper-controller.js
ui/src/app/pages/burn-coin/burn-coin.component.html
ui/src/app/pages/burn-token/burn-token.component.html
ui/src/app/pages/spend-coin/spend-coin.component.html
ui/src/app/pages/spend-coin/spend-coin.component.ts
ui/src/app/pages/spend-public-coin/spend-public-coin.component.html
ui/src/app/pages/spend-public-token/spend-public-token.component.html
ui/src/app/pages/spend-public-token/spend-public-token.component.ts
ui/src/app/pages/spend-token/spend-token.component.html
ui/src/app/pages/spend-token/spend-token.component.ts
zkp/code/gm17/nft-transfer/nft-transfer.pcode
zkp/contracts/ERC721TokenReceiver.sol

This PR is for changing the naming convention of recipient to receiver. This is done across all the microservices and docs.
**Please make sure that we need to merge [PR145](https://github.com/EYBlockchain/nightfall/pull/145) before merging this branch to master.**
PR #145 
- [] My change requires a change to the documentation.

Name change from recipient to receiver

---

docker-compose.test.yml
docker-compose.yml
zkp/code/index.js
zkp/config/default.js
zkp/config/test.js
zkp/package-lock.json
zkp/package.json
zkp/src/Element.js
zkp/src/compute-vectors.js
zkp/src/config.js
zkp/src/f-token-controller.js
zkp/src/f-token-zkp.js
zkp/src/index.js
zkp/src/nf-token-controller.js
zkp/src/nf-token-zkp.js
zkp/src/routes/ft-commitment.js
zkp/src/routes/nft-commitment.js
zkp/src/vk-controller.js
zkp/src/zokrates.js

config npm module implemented for zkp microservice. And, replaced usage of ```src/config.js``` with config module
fixes#171
Config module used for its few features
1. no need to have explicit logic to choose which config for which environment
2. Environment specific file should only have overriding config settings 
1. By running integration test ```./nightfall-test ``` script
2. By running UI and testing all features

implemented config module for zkp microservice

---

.gitignore
api-gateway/src/rest/accounts.js

fixes eslint issues - fixes breaking bug also.
updated .gitignore file for ```nightfall_test.log```
fixes #187 
1. By run integration test

fixes master eslint issue (bug-fix)

---

nightfall_test.log
zkp/code/gm17/ft-burn/ft-burn.code
zkp/code/gm17/ft-transfer/ft-transfer.code
zkp/code/gm17/nft-burn/nft-burn.code
zkp/code/gm17/nft-transfer/nft-transfer.code
zkp/src/f-token-controller.js
zkp/src/nf-token-controller.js

Combined path inputs into single field[32] array of (216 bit) fields, which allows for a more compact proof by replacing multiple lines with a for loop
None - this a reduction in code size but does not affect operation of the application
To create proof batching, the ZoKrates code will need to be larger.  Without this change, it would be hard to read.
Manual testing and nightfall integration test

feat(code) proofs presented in more compact form

---

README.md
zkp/README.md
zkp/package.json

PR #211 reverted broken changes in #119. This PR reintroduces those changes while fixing the cause of the errors.

Add zkp module documentation, for #119

---

package.json

This fixes the package name per #220
#220

Fix npm package name

---

SECURITY.md

Fix word styling

---

contributing.md

Add branching and commit message policies

feat(doc): add branching and commit message policies

---

.github/workflows/test-pull-request.yml

This makes swap allocation faster and removes speeds up testing build times.
#222
Slow builds increase waiting
Will review automated build output, after this PR triggers it

fix: make swap allocation fast, fixes #222

---

.github/workflows/test-pull-request.yml

Currently the test suite in GitHub Actions is run in serial. This switches to a parallel build.
- Reduce the concern of each build job
- Speed up testing
- Make local testing easier (so people will do it!)
Will run the test, which is triggered from this PR

Parallelize test suite

---

README.md

The provides a reference for setting up a Docker group on Linux and updates the documentation to match Docker recommendations.
N/A
Improve documentation
Ran the provided commands on Linux
Thank you to Damiano Shehaj for providing this fix.

Update Docker permissions documentation

---

docker-compose.yml

This PR is regarding the updates in docker-compose.yml file for the dependency updates of the api-gateway container.
- Running integration tests
- Running UI

Dependency updates on docker-compose file for api-gateway container

---

api-gateway/package.json
api-gateway/src/index.js
api-gateway/src/rest/zkp.js
api-gateway/src/routes/ft-commitment.js
api-gateway/src/routes/ft.js
api-gateway/src/routes/nft-commitment.js
api-gateway/src/routes/nft.js
api-gateway/src/routes/shield.js
api-gateway/src/routes/user.js
api-gateway/src/services/api-gateway.js
api-gateway/src/services/ft-commitment.js
api-gateway/src/services/ft.js
api-gateway/src/services/nft-commitment.js
api-gateway/src/services/nft.js
api-gateway/src/services/shield.js
integration-test/test.js
offchain/src/listeners.js
offchain/src/rest/api-gateway.js
ui/src/app/pages/user-accounts/user-accounts.component.ts
ui/src/app/services/accounts/accounts-api.service.ts
ui/src/app/services/coins/coin-api.service.ts
ui/src/app/services/tokens/token-api.service.ts

all APIs in api-gateway microservice follow RPC standards.
fixes#247
1. by running UI

api gateway microservice now comply with RPC standards

---

zkp/src/f-token-controller.js
zkp/src/routes/ft-commitment.js
zkp/src/routes/nft-commitment.js

Renames variables for ZKP functions to be more obvious without any additional context. No functional changes.
These changes will make variables more clear for developers who are unfamiliar with the project, and will help set the stage for future refactors. 
Ran ./nightfall-test

Rename variables for ZKP functions

---

zkp/src/f-token-controller.js
zkp/src/nf-token-controller.js
zkp/src/routes/ft-commitment.js
zkp/src/routes/nft-commitment.js

Renames variables within the controller functions themselves.

Rename controller variables

---

api-gateway/src/services/nft-commitment.js
zkp/src/routes/nft-commitment.js

Renamed ZKP variables in nft-commitment files

refactor: rename ZKP variable names

---

.github/workflows/test-pull-request.yml

Implemented new job to run zkp micoservice uint tests,  when pull request create to master branch
fixes #262 
By trying behaviour on event push on temporary branch

zkp unit tests job for github actions

---

.github/workflows/test-pull-request.yml
zkp/__tests__/nf-token-controller.test.js
zkp/package.json

The jest tests were using the wrong environment, this should fix everything.

Fix zkp unit tests

---

api-gateway/src/services/ft-commitment.js
zkp/src/routes/ft-commitment.js

Renamed variable names in ft-commitment.

refactor: rename ZKP route variables

---

zkp/src/f-token-zkp.js
zkp/src/nf-token-zkp.js
zkp/src/vk-controller.js

Removed wrapper functions and moved them to vk controller.

refactor: remove zkp wrapper functions

---

api-gateway/src/rest/zkp.js
api-gateway/src/routes/ft-commitment.js
api-gateway/src/services/ft-commitment.js
api-gateway/src/services/whisper.js
database/src/business/ft-commitment.service.js
database/src/mappers/ft-commitment-transaction.js
database/src/mappers/ft-commitment.js
database/src/models/ft-commitment-transaction.model.js
database/src/models/ft-commitment.model.js
docker-compose.yml
integration-test/test.js
integration-test/testData.js
zkp/README.md
zkp/src/f-token-zkp.js
zkp/src/routes/ft-commitment.js
zkp/src/routes/nft-commitment.js
zkp/src/zkpUtils.js

ft commitment batch transfer api implemented, this PR also resolve a bug in commitment transfer
Also Integration test updated with batch api test.
By running Integration test.

batch ft-commitment transfer api implemented

---

.github/workflows/test-pull-request.yml
.gitmodules

this PR update .gitmodules file to refer ```https``` url instead of ```ssh``` of sake github actions to work. 
Check this action run instance 
https://github.com/EYBlockchain/nightfall/runs/324668851

feat(github-actions): github workflow now setups submodules

---

api-gateway/src/rest/db.js
api-gateway/src/rest/zkp.js
api-gateway/src/routes/ft-commitment.js
api-gateway/src/services/api-gateway.js
api-gateway/src/services/ft-commitment.js

The PR is to replacing the coin naming in api-gateway to ft and ft-commitment. 
- Running integration test

Replacing the coin naming in api-gateway to ft and ft-commitment

---

PRODUCTION-USAGE.md

Explain best practices for production deployments
Ready to merge. But the file is draft, and it is noted as draft.
#300 Document DRAFT production deployment process
99% of compromises against systems are related to specific implementation/deployment issues rather than the mathematical security of the design.
We can start documenting best practices to keep people informed about some good policies to use with Nightfall.
No code changes.
Warnings added to show that file is in draft and that Nightfall should currently not be used for production use cases.
n/a

Create production usage notes, fixes #300

---

zkp/__tests__/utils.test.js
zkp/src/zkpUtils.js

Removed redundant functions in `zkpUtils` and respective tests.
Cleanup of historical functions.
Local unit and integration tests.

zkpUtils cleanup of redundant functions

---

package-lock.json
package.json

It's a small PR for changing all dependencies to devDependencies in the main package.json.
closes #302 
- Running integration test
- Running UI

Removing all dependencies to devDependencies in package.json

---

zkp/src/vk-controller.js

Small change to pull out loadVk into Nightlite.

Replace loadVk with nightlite version

---

api-gateway/src/services/ft-commitment.js
api-gateway/src/services/ft.js
api-gateway/src/services/whisper.js
database/src/business/ft-transaction.service.js
database/src/business/ft.service.js
database/src/mappers/ft.js
database/src/models/ft-transaction.model.js
database/src/routes/ft.routes.js
integration-test/test.js
offchain/src/listeners.js
ui/src/app/pages/ft-burn/index.ts
ui/src/app/pages/ft-mint/index.ts
ui/src/app/pages/ft-transfer/index.ts
ui/src/app/pages/overview/index.html
ui/src/app/services/ft.service.ts
zkp/src/routes/ft.js

This PR correct naming convention for `ft` across all microservices, also changes database schema for `ft`
1. By running UI
2. By running Integration test (```./nightfall-test```)

(ft) naming convention corrected

---

.github/workflows/re-run-pull-request-github-actions.yml

This PR correct a typo-mistake of commit message which get created from GitHub action workflow, so existing PRs can run their respective (integration-test & unit-test) GitHub actions.

(typo - mistake) correction at github actions 

---

.github/workflows/test-pull-request.yml
docker-compose.yml

This PR fix 'ran out of disk space' issue with github action workflow
By creating a temporary branch executing github actions there.
https://github.com/EYBlockchain/nightfall/runs/467136664

fix github-actions disk space ran out issue

---

.github/workflows/test-pull-request.yml
README.md
docker-compose.yml

Removes unnecessary github login and updates github actions as per Timber migration to Dockerhub. 
#381 
Github login is no longer necessary, updates to `README.md`  to reflect this change.
Tested via `./nightfall-test`

chore: update readme and actions

---

.github/workflows/re-run-pull-request-github-actions.yml

This PR is generated for two things
1. updates github actions workflow `Re-run Pull-Request's last github actions` to remove unnecessary steps.
2. to check what made github workflow `Run Nightfall test suite` to fail for PR generate from a forked repo

remove unnecessary steps from github workflow

---

zkp/contracts/FTokenShield.sol

Ensures output of FToken.transferFrom and .transfer is true before completing mint and burn.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
- [ x ] All new and existing tests passed.

FTokenShield mint/burn functions now check FToken.transferFrom/transfer output

---

.github/workflows/test-pull-request.yml
integration-test/test.js
integration-test/testData.js
zkp/__tests__/nf-token-controller.test.js
zkp/contracts/NFTokenShield.sol
zkp/migrations/2_Shield_migration.js
zkp/package-lock.json
zkp/package.json
zkp/src/nf-token-controller.js
zkp/src/nf-token-zkp.js
zkp/src/routes/nft-commitment.js

Update application to accept multiple ERC721 contracts.

Multiple erc721

---

.github/workflows/test-pull-request.yml
database/config/default.js
docker-compose.yml
integration-test/test.js
integration-test/testData.js
nightfall-test
package.json

`./nightfall-test` bash script to configured to run compliance setting. By running. `./nightfall-test compliance`
By running integration test

compliance integration test configured

---

database/setup-mongo-acl-for-new-users.js

Fixes a bug in mongo script, which run as a child process at Signup. 
fixes #396 
By running UI

bug resolved - SignIn and SignUp

---

zkp/contracts/FTokenShield.sol

small bug in the gas measurement of the fTokenShield.sol contract.

chore: gas measurement

---

.github/workflows/test-pull-request.yml
api-gateway/src/rest/db.js
api-gateway/src/services/ft-commitment.js
api-gateway/src/services/nft-commitment.js
database/src/business/ft-commitment.service.js
database/src/mappers/ft-commitment.js
database/src/models/ft-commitment.model.js
integration-test/test.js
integration-test/testData.js
nightfall
nightfall-test
offchain/src/listeners.js
package.json
ui/package-lock.json
ui/package.json
ui/src/app/feature/nav/nav.component.ts
ui/src/app/pages/ft-commitment-consolidation-transfer/index.ts
ui/src/app/pages/ft-commitment-list/index.css
ui/src/app/pages/ft-commitment-list/index.html
ui/src/app/pages/ft-commitment-list/index.ts
ui/src/app/services/ft-commitment.service.ts
zkp/src/routes/ft-commitment.js

other than below list of bug fixes - this PR add compliance integration test to github actions workflow
1. fixes #424  (error caused by `mongo-merkle-tree` microservice not fully initialised before  'merkle-tree' micorservice calling it).
2. UI microservice - implemented missing pagination in ft-commitment list page
3. database microservice - (Batch transfer) now store change data in outputCommitments array of transaction log
4. configure consolidation transfer to implement rabbitMQ
5. updated integration test - consolidation transfer input now depend on result of batch transfer
6. updated `offchain/src/listeners.js` to fixes commitmentIndex bug, since now commitmentIndex expected decimal instead of hexadecimal.
By running UI
By running integration test

bug fixes & added github actions workflow for compliance integration test

---

zkp/contracts/FTokenShield.sol
zkp/contracts/NFTokenShield.sol
zkp/contracts/PublicKeyTree.sol

refactor `zkp/contracts` files
fixes #410 
fixes #409 
fixes #408

refactor zkp contracts

---

README.md
zkp/src/routes/ft-commitment.js

Readme.md for mac hardware & prerequisites updated

---

accounts/src/app.js
api-gateway/src/index.js
api-gateway/src/rest/accounts.js
api-gateway/src/rest/db.js
api-gateway/src/rest/offchain.js
api-gateway/src/rest/zkp.js
api-gateway/src/services/api-gateway.js
database/setup-mongo-acl-for-new-users.js
database/src/index.js
offchain/src/index.js
offchain/src/rest/api-gateway.js
zkp/src/index.js

This is a PR to update inline callback functions as an arrow functions. Which is recommended by Airbnb coding standards.
closes #427 
- Running Integration tests
- Running UI

Update inline callback functions as arrow functions

---

accounts/src/middlewares/index.js
api-gateway/src/middlewares/index.js
api-gateway/src/rest/index.js
api-gateway/src/routes/index.js
database/src/business/index.js
database/src/mappers/index.js
database/src/middlewares/index.js
database/src/models/index.js
database/src/mongodb/db.js
database/src/routes/index.js
offchain/src/middlewares/index.js
zkp/src/middlewares/index.js
zkp/src/routes/index.js

This is a PR to avoid direct exports from imports in certain files as per Airbnb standards.
Closes Issue #428 
- Running UI
- Running integration tests

Avoiding exports directly from imports

---

zkp/__tests__/consolidation-mimc.js
zkp/__tests__/f-token-controller-rc.js
zkp/__tests__/simple-batch.js
zkp/package-lock.json
zkp/package.json
zkp/src/routes/ft-commitment.js

batch transfer logic refactored in nightlite this PR includes code logic to accommodate the update
fixes #379 
By running integration test

refactor batch transfer

---

zkp/__tests__/consolidation-mimc.js
zkp/__tests__/f-token-controller-rc.js
zkp/__tests__/f-token-controller.js
zkp/__tests__/nf-token-controller.js
zkp/__tests__/setups/override-default-config.js
zkp/__tests__/simple-batch.js
zkp/package-lock.json
zkp/package.json
zkp/src/index.js

This PR update nightlite version in zkp microservice and calls `overrideDefaultConfig` of nightlite module.
By running integration test

nightlite 'overrideDefaultConfig' function called

---

accounts/src/routes/accounts.js
api-gateway/src/index.js
api-gateway/src/middlewares/auth.js
api-gateway/src/middlewares/index.js
api-gateway/src/middlewares/password.js
api-gateway/src/rest/zkp.js
api-gateway/src/services/api-gateway.js
api-gateway/src/services/ft-commitment.js
api-gateway/src/services/nft-commitment.js
api-gateway/src/services/nft.js
api-gateway/src/services/whisper.js
api-gateway/src/setup-admin-user.js
database/src/models/ft-commitment.model.js
database/src/models/nft-commitment.model.js
database/src/routes/user.routes.js
integration-test/test.js
ui/src/app/pages/ft-commitment-batch-transfer/index.ts
zkp/src/compliance-init.js
zkp/src/contractUtils.js
zkp/src/f-token-controller.js
zkp/src/f-token-zkp.js
zkp/src/nf-token-controller.js
zkp/src/nf-token-zkp.js
zkp/src/padme.js
zkp/src/routes/ft-commitment.js
zkp/src/routes/nft-commitment.js
zkp/src/routes/nft.js
zkp/src/vk-controller.js
zkp/src/zkpUtils.js

fixes #430 
By running Integration and UI

documentations: (comments) standards corrected
