EYBlockchain/nightfall

- .gitattributes
By adding a .gitattributes file to identify *.sol files as Solidity
> Enable Solidity syntax highlighting on GitHub

- README.md
I tried to run with node v12, but was unsuccessful. I finally figured out that node v10 was what would get it to work. (Yes, despite that the comment that was there; I thought the v10.15.3 was referring to the beta for OSX.)
> add more info about python/node version

- README.md
- security-updates.md
- zkp/contracts/FTokenShield.sol
Bug found by @benjamindelmee 
Affects only the ft-transfer.
Added two `require` statements:  
- to ensure the nullifiers N_c and N_d are different (to avoid double-spend of Z_c by publishing N_c and a second N_c).
- to prevent Alice from accidentally sending duplicate Z_e and Z_f values.
The underlying node.js application would never have created this scenario, but people using the smart contracts more generally could have exploited this.
Updated the 'Security Updates' section of the README.
Moved the bulk of the 'Security Updates' body of text from the README to its own file `security-updates.md`, because it was becoming too big for the 'front page' readme.
> fix: security update - prevent duplicate nullifier - ft-transfer.

- zkp/contracts/NFTokenShield.sol
Use the ERC-721 interface instead of non-fungible token implementation in `NFTokenShield.sol`.
> NFTokenShield interface for NFT

- .travis.yml
This adds a basic Travis file so that Travis builds may be turned on for this repository.
Of course this test script can be improved. But *some* test script is required to turn on builds. And it is easier to improve the script when builds are turned on.
> Add basic Travis file

- API-Gateway/src/services/coin.js
- API-Gateway/src/services/token.js
- database/src/business/coin.service.js
- database/src/business/coin_transaction.service.js
- database/src/mappers/coin-transaction.js
- ui/src/app/pages/burn-coin/burn-coin.component.html
- ui/src/app/pages/burn-coin/burn-coin.component.ts
- ui/src/app/pages/burn-token/burn-token.component.html
- ui/src/app/pages/burn-token/burn-token.component.ts
- ui/src/app/pages/overview/overview.component.html
- ui/src/app/services/coins/coin-api.service.ts
- ui/src/app/services/tokens/token-api.service.ts
- zkp/src/index.js
**Earlier**:
The users could only burn off "ERC20/ERC721 token commitments" and transfer generated "ERC20/ERC721 tokens" to themselves.
**Enhancement**:
Now, The users could burn off "ERC20/ERC721 token commitments" and transfer generated "ERC20/ERC721 tokens" to themselves or other users.
-- Added user selection option in burn page of ERC20/ERC721 token commitment (UI)
-- Populate transferee in ERC20/ERC721 token commitment tab of overview page (UI)
-- Passed `payTo` parameter to ZKP micro-service (backend)
-- Saved and retrieved transferee details in transaction API of DB micro-service (backend) 
fixes#37
> Feature: Burn ERC20/ERC721 token and transfer

- API-Gateway/src/index.js
- API-Gateway/src/routes/ft_commitment.js
- API-Gateway/src/routes/nft_commitment.js
- API-Gateway/src/services/ft_commitment.js
- API-Gateway/src/services/nft_commitment.js
- ui/src/app/pages/mint-coin/mint-coin.component.ts
- ui/src/app/pages/mint-token/mint-token.component.ts
- ui/src/app/pages/spend-coin/spend-coin.component.ts
- ui/src/app/pages/spend-token/spend-token.component.ts
- ui/src/app/services/coins/coin-api.service.ts
- ui/src/app/services/tokens/token-api.service.ts
- zkp/src/index.js
Moved salt generation logic of ERC20/ERC720 token commitment for Mint and Transfer from UI to ZKP microservices and reduced the dependency.
Earlier salt generation logic of ERC20/ERC720 token commitment for Mint and Transfer is placed in UI side.  To reduce that dependency and make the ZKP microservice as independent as possible, moved that logic to ZKP microservice. 
Tested using UI
- [] Breaking change (fix or feature that would cause existing functionality to change)
> Asish.ap/moved salt generation to zkp

- database/src/business/token.service.js
Fixed ERC721 token is listed after burn in listing page.
ERC721 token is listed after burn in listing page.
**Steps to reproduce:**
1. Alice minted a NFT
2. Alice minted the same NFT to NFT commitment
3. Transfer NFT commitment to Bob
4. Bob burns that NFT commitment
5. Bob transfer NFT token to Alice
6. Alice burns that token.
Ideally after burned a NFT token, it shouldn't be appear in listing page. 
This issue is fixed by adding a shield flag when updating the NFT token.
Tested via UI
> fix(database): NFToken listed after burn in token listing page.

- ui/src/app/pages/burn-public-coin/burn-public-coin.component.html
- ui/src/app/pages/burn-public-coin/burn-public-coin.component.ts
- ui/src/app/pages/mint-coin/mint-coin.component.html
- ui/src/app/pages/mint-public-coin/mint-public-coin.component.html
- ui/src/app/pages/mint-public-coin/mint-public-coin.component.ts
- ui/src/app/pages/spend-public-coin/spend-public-coin.component.html
- ui/src/app/pages/spend-public-coin/spend-public-coin.component.ts
- ui/src/app/services/utils/util.service.ts
Limit the text field to enter numbers only in mint, burn, transfer of ERC20 token pages.
Using UI if user entered characters instead of numbers when Mint, Transfer, Burn of ERC20 token it will hang and get the following error on terminal
```
zkp_1               | { Error: invalid number value (arg="_amount", coderType="uint256", value="ksdfg")
zkp_1               |     at Object.throwError (/app/node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:17)
zkp_1               |     at CoderNumber.encode (/app/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:353:20)
zkp_1               |     at /app/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:605:59
zkp_1               |     at Array.forEach (<anonymous>)
zkp_1           
```
To fix this issue …
> fix(ui): Limit the text field to enter numbers only

- README.md
Updates `docker-proxy` install link in README.md to `dotdocker`.
Closes issue #52 
The tool `docker-proxy` has been completely rebuilt as `dotdocker`, which supports more operating systems.
Changes to the code are only in README.md. I have tested basic Nightfall functionality using `dotdocker` and have not encountered any errors. Needs additional testing **for Linux machines.** Please try testing on Linux.
> chore:change docker-proxy to dotdocker

- README.md
This PR documents and links the nightfall truffle box into the README.
Figured this would be the most elegant way to reference the box, open to suggestions!
> Documentation: reference the truffle nightfall-box

- ui/src/app/pages/create-accounts/create-accounts.component.html
- ui/src/app/pages/create-accounts/create-accounts.component.ts
- ui/src/app/services/utils/util.service.ts
Restrict user name field to lower case letters when creating a new account
#76 
Throwing 500 internal server error when creating a user with capital letters. Internally in nightfall we are dynamically creating collections based on user name. Every user have their own collections and collections name would be prefixed with his/her username. We observed that mongo does n't allow to create collection name with capital letters and it automatically changes the name to lower case. So during the account creation we are applying ACL to the mongo collections based on user name and mongo could n't recognise the collection name with small letters.
As a solution will restrict to lower case letters in user name field from the UI.
Tested using UI
> Restrict user name field to lower case while registering.

- limitations.md
This migrates a security note from the white paper into the other security notes in the known limitations pages.
> Add security note on outdated ZoKrates version

- security-updates.md
- zkp/contracts/FTokenShield.sol
- zkp/contracts/NFTokenShield.sol
Shield contracts now check that nullifier public inputs are smaller than the prime field used by ZoKrates.  This prevents the following double spend attack where `nullifier_hash + 21888242871839275222246405745257275088548364400416034343698204186575808495617 = nullifier_hash mod 218.....617` will pass snark proof verification if it fits into uint256 but will not be in the list of nullifiers held by the shield contract, allowing double spend.
fixes #95
Prevents a type of double spend attack
This was tested using the ./zkp-demo-test script.
N/A
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests …
> fix(zkp): added nullifier overflow prevention to shield contracts

- API-Gateway/Dockerfile
- accounts/Dockerfile
- database/Dockerfile
- offchain/Dockerfile
- ui/Dockerfile
- zkp/Dockerfile
> The WORKDIR instruction sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow it in the Dockerfile. If the WORKDIR doesn’t exist, it will be created even if it’s not used in any subsequent Dockerfile instruction.
> 
> Source https://docs.docker.com/engine/reference/builder/
Therefore it is unnecessary to have a `mkdir` before the `WORKDIR`.
> Remove redundant mkdir

- nightfall
- nightfall-test
run 'npm ci' instead of 'npm i', thus use package-lock.json to install dependencies
fixes#110
avoid changes package-lock.json if dependent module have updated versions 
1. by running integration test
2. and by using UI.
> zkp-utils dependencies installation using 'npm ci'

- nightfall-test
Remove volume and network if 'docker-compose down' failed to do so
fixes#155
1. Integration test
2. by running UI
> explicit removal volume and network when integration test ends

- docker-compose.test.yml
- docker-compose.yml
Switch to always use port numbers specified as strings in Docker Compose.
#162 Always specify port numbers as strings
This is an official Docker Compose recommendation as cited above.
Ran Docker build.
Personally, I like to collect a large bibliography for things like this where we will recognize best practices and style guides. You can see an example at https://github.com/fulldecent/aion-aip040#references
I have cited the reference in the related issue above and will be happy to maintain a references list if we will add it to this project.
> Always use string for port numbers

- zkp/src/contractUtils.js
- zkp/src/f-token-controller.js
- zkp/src/nf-token-controller.js
- zkp/src/routes/ft-commitment.js
- zkp/src/routes/nft-commitment.js
Pulls getters for vkId and contract details out of the ZKP functions
The ZKP functions as-is make a lot of assumptions as to where certain files are stored. For example, they assume that the vk IDs are stored in a JSON file in a certain location in the file system. Other applications may not have these same assumptions, for example, VKIDs may be stored in MongoDB. 
Additionally, these functions assume that the rest of the application is using truffle-contract, but other applications may be using ethers, or web3. By supplying the JSON and the address, and reinstantiating the contract object within the function, these functions are now agnostic of what the rest of the application is using.
> Pull out getters (Dependent on #245)

- zkp/README.md
In the README, there is a line stating that there is a key generation recipe in the Makefile. That recipe no longer exists. 
This will prevent future users from being confused.
Verified that there is indeed no way to generate keys from Makefile. Checked the Markdown to make sure nothing else was deleted. 
comment fix
> take out line "has recipe in makefile"

- zkp-utils/index.js
- zkp/__tests__/utils.test.js
These functions aren't being used in the codebase currently. It's best practice to remove unused code to keep the codebase small. If we need these functions in the future, we can get them back through git.
> Remove unused zkp-util code

- .eslintignore
- .github/workflows/test-pull-request.yml
- docker-compose.yml
- package-lock.json
- package.json
- zkp/Dockerfile
- zkp/README.md
- zkp/__tests__/f-token-controller.test.js
- zkp/__tests__/nf-token-controller.test.js
- zkp/__tests__/utils.test.js
- zkp/code/README-trusted-setup.md
- zkp/code/config.js
- zkp/code/index.js
- zkp/code/keyExtractor.js
- zkp/package-lock.json
- zkp/package.json
- zkp/src/Element.js
- zkp/src/compute-vectors.js
- zkp/src/f-token-controller.js
- zkp/src/f-token-zkp.js
- zkp/src/nf-token-controller.js
- zkp/src/nf-token-zkp.js
- zkp/src/routes/ft-commitment.js
- zkp/src/vk-controller.js
- zkp/src/zkpUtils.js
This PR uses zokrates.js instead of the nested docker container. This greatly simplifies a lot of the logic, and makes the code a lot cleaner to read.
I wasn't sure about how much of the filingChecks functionality was still used, I left it all in but maybe we could remove it if it's legacy code.
> Refactor setupAll, pull in zokrates.js

- zkp/__tests__/loadVK.js
- zkp/__tests__/test-environment.js
- zkp/package.json
This PR modify existing behaviour of asynchronously loading of vkIDs parallelly to test, to asynchronously loading of vkIDs sequentially to test.
By run zkp unit test locally
> (zkp-unit-test) load all vkIds at first

- nightfall-test
Currently, ```./nightfall-test``` is not exiting with error, if integration test failed. This PR fixes that, so that github actions to check . integration test should fails
By run integration test
> fix(github actions):  exit with error if integration test failed

- ui/src/app/pages/ft-commitment-transfer/index.html
- ui/src/app/services/utils/util.service.ts
fixes to UI ft-commitment-transfer page. Now no negative value allowed to transfer from UI
fixes #276 
by running UI
> (bug fix) ft commitment transfer page - no negative number allowed

- zkp/src/f-token-controller.js
- zkp/src/index.js
- zkp/src/nf-token-controller.js
- zkp/src/sdkProvider.js
- zkp/src/vk-controller.js
Although this change seems redundant, having a separate provider manager for the functions that will eventually be pulled out for the SDK will make things go much more smoothly later on. That way we can pull out the `sdkProvider` with the rest of the functions and be more agnostic about what libraries we're using.
> Pull out provider into own folder for sdk prep

- zkp/src/contractUtils.js
- zkp/src/vk-controller.js
This PR makes the VK functions more encapsulated, so that the `loadVk()` function operates agnostically of whatever backend library (i.e., ethers, web3, truffle-contract) is being used.
The provider still needs to be pulled out at some point, but that will be a later PR.
> Encapsulate VK Functions

- api-gateway/src/services/ft-commitment.js
- api-gateway/src/services/nft-commitment.js
- offchain/src/listeners.js
- zkp/__tests__/nf-token-controller.test.js
- zkp/src/f-token-controller.js
- zkp/src/f-token-zkp.js
- zkp/src/nf-token-controller.js
- zkp/src/nf-token-zkp.js
- zkp/src/rest/merkle-tree.js
- zkp/src/routes/ft-commitment.js
- zkp/src/routes/nft-commitment.js
The `blockNumber` of a transfer & burn is now shared from Alice to Bob. Bob can then poll his merkle-tree db until is has filtered this block. He can then query whether his new commitment does indeed exist within the Merkle Tree at the specified index.
fixes #330 
Fixes a race condition bug, where Bob was querying his db before the event filter had necessarily picked up the tx.
Integration test & unit tests & manual UI tests transferring / burning from Alice to Bob and checking Bob's 'transaction history' pages correctly 'pick up' the required info.
> fix: Race condition - checking correctness of received commitment

- nightfall-generate-trusted-setup
We have quite a bit of identical code in our proofs (ZoKrates dsl).  This could easily be refactored into a common directory.  Unfortunately the trusted setup would attempt to build any such code, which would fail as it would not intended to be compiled as a stand-alone proof.  To fix that, I've altered the `./nightfall-generate-trusted-setup` script to ignore a directory named 'common'.  This gives us a place to store functions common to multiple proofs.
Fixes #344
Tested by running `./nightfall-generate-trusted-setup` script and checking manually for correct operation (code in `common` folder is ignored)
> trusted setup now ignores common folder

- README.md
Adds documentation on generating an access token, now necessary for the inclusion of `timber`.
> Add access token documentation

- nightfall-generate-trusted-setup
- zkp/code/index.js
- zkp/package.json
bug resolved as option '-i' was taken by babel-node options instead of code/index.js argument
fixes #361 
By running  `./nightfall-generate-trusted-setup `
> trusted setup bug resolved

- docker-compose.yml
Unit tests no longer run correctly locally because the zkp container starts before the merkle-tree service: a dependency is missing
fixes #364
> fix unit tests not running locally

- .github/workflows/re-run-pull-request-github-actions.yml
This PR add new github workflow file ```re-run-pull-request-github-actions.yml``` which will trigger when a PR is merged to master, and workflow will also push an empty commit to existing PR to trigger ```test-pull-request.yml``` PR test github action workflow
Outdated PRs check were wrongly consider to successful ran against frequently updating master branch  
code has been test in temporary branch ```liju.jose/configure-github-actions-4``` and test for PR #297 by logically creating an empty commit #eed99c238e778d930db7241f3d853afcaa8dcad9
> trigger test-pull-request.yml github action on existing outdated PRs

- nightfall-generate-trusted-setup
Fixes ./nightfall-generate-trusted-setup error when gm17 doesn't exist.
Creates folder if code/gm17 cannot be found.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] All new and existing tests passed.
> fix: creates gm17 folder if doesn't exist

- zkp/contracts/FTokenShield.sol
- zkp/contracts/NFTokenShield.sol
The RegisterVerificationKey functions in both shield contract do not return any value, instead they emit an event. This PR removes the expected bytes32 value from them.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
- [ x ] All new and existing tests passed.
> Removed 'returns' from RegisterVerificationKey functions

- README.md
Removed the link to Nightfall Truffle Box.
Trusted Setup Failing #334
Nightfall Truffle Box requires maintenance and has been outdated since December.
Tested on Wednesday Feb 26. Box fails at npm run set up.
System:
macOS 10.14.6, 16GB ram
docker 2.1.1.0.5
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
> fix: truffle box requires maintenance

- nightfall
- nightfall-test
update `./nightfall` and `./nightfall-test` bash script to close containers and deleted generated files before exiting.
fixes #442
> close container at the end of nightfall bash scripts

- nightfall-generate-trusted-setup
Fixes bug for MiMC hash, cases where after generating setup (by running `nightfall-generate-trusted-setup` script) user try to zkp unit tests
By running zkp uint test
> fixes nightfall-generate-trusted-setup script
